auto-commit: updated files

diff --git a/fortune b/fortune
--- a/fortune
+++ b/fortune
@@ -50,19 +50,21 @@ elif [ "$1" = "--edit" ]; then
     _update_dat_files
 
 elif [ "$1" = "--push" ]; then
-    # Quick push to remote
-    cd "$DIR" || exit 1
-
-    _update_dat_files
+    read -p "Auto-committing and pushin to remote. Continue? [y/N] " answer
+    case "$answer" in
+        [Yy]*) echo "Continuing...";;
+        *)     echo "Aborted."; exit 1;;
+    esac
     set -x
+    cd "$DIR" || exit 1
+    _update_dat_files
     git add .
     git commit -m "auto-commit: updated files"
     git push 
-    set +x
 
 # Bad arguments
 else
-    echo "Usage: ./fortune [ --update | --search query | --fzf | --edit ]"
+    echo "Usage: ./fortune [ --update | --search query | --fzf | --edit | --push ]"
 fi 
 
 exit 0
